### ISSUE TITLE
Type PromiseMock<T> is not assignable to type Promise<T>

### ISSUE THREAD

**Issue by martindzejky** [slavik57/promise-sync#15]
![image](https://user-images.githubusercontent.com/4700122/68992885-c48b1f80-0871-11ea-94fa-8cdfaddaa2db.png)

Hello, `PromiseMock` is not assignable to a variable or a parameter that expects the type `Promise`. The error returned by Typescript is this:

```Property '[Symbol.toStringTag]' is missing in type 'PromiseMock<T>' but required in 'Promise<T>'```

This makes it hard to use the promise mock in places where a real promise is expected, resulting in us having to cast the value to `any`. 😞 

### Versions

- `promise-sync@1.1.7`
- `typescript@3.6.4`

**Comment by slavik57** [comment]
I'm sorry, but I don't have the time capacity to fix this since it would require a lot of changes since the Promise interface has changed a lot in the newer versions of Typescript.
If you can create a pull request with the minimal needed changes and tests that pass I would review it and merge it.

**Comment by martindzejky** [comment]
Hello @slavik57 and anyone who ends here in the future. I tried making a PR for your repository but I just could not make it work. So, I ended up making my own repository and library for a promise mock which implements the full Typescript `Promise<T>` interface. I linked back to your original implementation.

https://github.com/martindzejky/promise-mock

If you need me to add any information to my repo, just let me know. Cheers!
