### ISSUE TITLE
Real sync promise

### ISSUE THREAD

**Issue by dy** [slavik57/promise-sync#6]
Hi @slavik57!

Very nice idea, very nice fit for the absent node API.
But actually it could’ve been done with [sync](https://www.npmjs.com/package/sync) or [fibers](https://www.npmjs.com/package/fibers) so that it could be used not only for testing/debugging purposes, but for so great deals like [glslify-promise](https://github.com/stackgl/glslify-promise) etc.

**Comment by slavik57** [comment]
Thank you for the constructive comment.
The pupropse was testing and mocking the Promise behaviour without changing the API of the Promise so that no real code needs to be changed
