### ISSUE TITLE
Compilation errors with current Typescript 1.8.10

### ISSUE THREAD

**Issue by kirill-chaban** [slavik57/promise-sync#8]
PromiseMock.d.ts has a following line:
`readonly state: PromiseState;`
Readonly properties will be available starting from typescript 2.0 https://github.com/Microsoft/TypeScript/pull/6532
So now there are compilation errors at this line.

Added PR: https://github.com/slavik57/promise-sync/pull/9

**Comment by slavik57** [comment]
The generation of the d.ts is automatic, probably I can set the TypeScript version in the tsconfig.json compiler options. I will look into it today.

Thanks!

**Comment by slavik57** [comment]
I couldn't find any way to define the compiler version in the tsconfig.json
So I added a setter to the property that throws error...

Such a shame they don't support it yet because it should be compilation and not runtime error when there is no setter for a property.
